version: '3.7'
networks:
  backend:
  frontend:

volumes:
  mongo-data:

services:
  mongo:
    image: mvertes/alpine-mongo:4.0.5-0
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend

  frontend:
    image: ${COMPOSE_PROJECT_NAME}-frontend:${TAG_FRONTEND}
    networks:
      - frontend
    depends_on:
      - api

  api: 
    image: ${COMPOSE_PROJECT_NAME}-api:${TAG_API}
    command: gunicorn --log-level=debug --workers=2
    networks:
      - frontend
      - backend
    environment:
      - SECRET_KEY_FILE=/run/secrets/api_secret
    depends_on:
      - mongo
      - redis

  worker:
    image: ${COMPOSE_PROJECT_NAME}-api:${TAG_API}
    command: celery -A task worker
    networks:
      - backend
    environment:
      - SECRET_KEY_FILE=/run/secrets/api_secret
    depends_on:
      - redis

  mongo-express:
    image: mongo-express
    networks:
      - backend

  worker_monitor:
    image: ${COMPOSE_PROJECT_NAME}-api:${TAG_API}
    command: "celery -A task flower"
    networks:
      - backend
    environment:
      - SECRET_KEY_FILE=/run/secrets/api_secret
