version: '3.7'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  mongo-data:
    driver: local

services:
  mongo:
    ports:
      - 27017:27017

  frontend:
    ports:
      - 80:80

  api: 
    volumes:
      - ./api:/code
      - ./secrets/api_secret_dev:/run/secrets/api_secret
    ports:
      - 5000:5000

  worker:
    volumes:
      - ./api:/code
      - ./secrets/api_secret_dev:/run/secrets/api_secret

  mongo-express:
    ports:
      - 8081:8081

  worker_monitor:
    volumes:
      - ./secrets/api_secret_dev:/run/secrets/api_secret
    ports:
      - 5555:5555
