version: '3.7'

volumes:
  mongo-data:
    driver: local

services:
  mongo:
    ports:
      - 27017:27017

  ui:
    ports:
      - 80:80

  api:
    volumes:
      - ./api:/code
    ports:
      - 5000:5000

  worker:
    volumes:
      - ./api:/code

  mongo-express:
    ports:
      - 8081:8081

  worker_monitor:
    ports:
      - 5555:5555
