version: '3.7'

volumes:
  mongo-data:

services:
  mongo:
    image: mvertes/alpine-mongo:4.0.5-0
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine

  ui:
    image: neosapience/appname-ui:dev
    depends_on:
      - api

  api: 
    image: neosapience/appname-api:dev
    command: gunicorn --log-level=debug -k gevent
    environment:
      - SECRET_KEY_FILE=/run/secrets/api_secret
    depends_on:
      - mongo
      - redis

  worker:
    image: appname-api:dev
    command: celery -A task worker
    environment:
      - SECRET_KEY_FILE=/run/secrets/api_secret
    depends_on:
      - redis

  mongo-express:
    image: mongo-express

  worker_monitor:
    image: appname-api:dev
    command: "celery -A task flower"
    environment:
      - SECRET_KEY_FILE=/run/secrets/api_secret
