apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

# resources:
# - ingress.yaml

namespace: appname

configMapGenerator:
- name: appname-api-config
  env: config.env

secretGenerator:
- name: api-secret
  files:
  - secret-api