apiVersion: v1
kind: Service
metadata:
  namespace: database
  name: mgo-ui
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: mongo-express

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: database
  name: mongo-express
  labels:
    app: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:0.49.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: ""
        - name: ME_CONFIG_MONGODB_URL
          value: mongodb://mgo:27017/
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              key: user
              name: mgo-auth
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mgo-auth
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              key: user
              name: mgo-auth
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mgo-auth
        - name: ME_CONFIG_OPTIONS_EDITORTHEME
          value: lucario
        livenessProbe:
          httpGet:
            path: /
            port: 8081
            httpHeaders:
              - name: Authorization
                value: Basic dXNlcjpwYXNz
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: 8081
            httpHeaders:
              - name: Authorization
                value: Basic dXNlcjpwYXNz
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "200m"
