apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: database
  name: mgo-auth
data:
  user: dXNlcg==
  password: cGFzcw==
---
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  namespace: database
  name: mgo
spec:
  version: "4.0.5-v1"
  storageType: Durable
  storage:
    storageClassName: "gp2"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
  databaseSecret:
    secretName: mgo-auth
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

