apiVersion: v1
kind: Service
metadata:
  name: appname-api
spec:
  selector:
    app: appname-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appname-api
  name: appname-api
spec:
  selector:
    matchLabels:
      app: appname-api
  template:
    metadata:
      labels:
        app: appname-api
    spec:
      volumes:
      - name: api-secret
        secret:
          defaultMode: 256
          secretName: api-secret
      containers:
      - name: appname-api
        args: ["gunicorn", "-k", "gevent"]
        # command: ["tail", "-f", "/dev/null"]
        envFrom:
        - configMapRef:
            name: appname-api-config
        imagePullPolicy: Always
        image: neosapience/appname-api:0.0.1
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 500m
            memory: 1000Mi
        volumeMounts:
        - mountPath: /run/secrets/app
          name: api-secret
          readOnly: true
        env:
        - name: SECRET_KEY_FILE
          value: /run/secrets/app/secret-api
