apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appname-worker
  name: appname-worker
spec:
  selector:
    matchLabels:
      app: appname-worker
  template:
    metadata:
      labels:
        app: appname-worker
    spec:
      volumes:
      - name: api-secret
        secret:
          defaultMode: 256
          secretName: api-secret
      containers:
      - name: appname-worker
        args: ["celery", "-A", "task", "worker"]
        envFrom:
        - configMapRef:
            name: appname-api-config
        imagePullPolicy: Always
        image: neosapience/appname-api:0.0.1
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 300Mi
        volumeMounts:
        - mountPath: /run/secrets/app
          name: api-secret
          readOnly: true
        env:
        - name: SECRET_KEY_FILE
          value: /run/secrets/app/secret-api
